### ISSUE TITLE
Interfacing with R

### ISSUE THREAD

**Issue by HaoZeke** [TheochemUI/eOn#38]
## Tasks
- [ ] Pass potentials created in R
  - Needs to accept an R function pointer
- Run EON methods
  - [X] NEB
- [X] Return values [Matter]
  - [X] I/O will do for now
## Problems
- The row major flag in Eigen
  - Unsupported by RCppEigen
- The logging
  - Can be replaced with RCppSpdlog

**Comment by HaoZeke** [comment]
Closing as not pursued: R language interfacing has no active consumers in the current roadmap; reopen with a user request and design if needed.

**Comment by HaoZeke** [comment]
Reopened: closed in triage by mistake; keep open per maintainer direction (2026-06-27).
